import NavBar from '@/Ccomponents/navbar'
import '@/styles/globals.css'
import Head from 'next/head'
 import Link from 'next/link'

export default function App({ Component, pageProps }) {
  return( 
  <>
  <Head>
        <title>Blog-App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"/>
         <script defer src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
            
      </Head>
      <NavBar/> 
  <Component {...pageProps} />
  </>
  )
}
